package imagescontroller;

/**
 * This is a enum which contains all the success messages after operation
 * performed.
 * 
 * @author ananth
 *
 */
public enum AcceptStrings {
  VIEWSETFEATURES, VIEWREPLACEDMCCOLOR, VIEWGETREPLACECOLOR, VIEWCROSSSTITCH, VIEWSETIMG,
  UPDATEDMCINDEX, GETUSERDMCINDEX, GETCOMPLETEDMCINDEX, SETVIEW, IMAGEREAD, IMAGEWRITE, BLUR,
  SHARPEN, DITHER, BATCHSCRIPTEXECUTED, GREYSCALE, SEPIATONE, MOSIAC, PIXELLATION,
  CROSSSTITCHPERFORMED, WRITECROSSSTITCHFILE, IMAGECONVERTEDTODMCCOLORS, REMOVEDDMC, REPLACEDDMC,
  ADDTEXT, CREATEDOWNDMCINDEX, WRITTENOWNDMCINDEX
}
